In [1]:
#import dependencies
import pandas as pd

In [2]:
#read in deaths data
deaths_df = pd.read_csv("Resources/Weekly_deaths.csv")

C:\Users\lmsul\anaconda3\envs\PythonData\lib\site-packages\IPython\core\interactiveshell.py:3147: DtypeWarning: Columns (7) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
deaths_df

,Data As Of,Start Date,End Date,Group,Year,Month,MMWR Week,Week-Ending Date,HHS Region,Race and Hispanic Origin Group,Age Group,COVID-19 Deaths,Total Deaths,Footnote
0,04/21/2021,12/29/2019,01/04/2020,By Week,2019/2020,NaN,1.0,01/04/2020,United States,Hispanic,0-4 years,0.0,104.0,NaN
1,04/21/2021,12/29/2019,01/04/2020,By Week,2019/2020,NaN,1.0,01/04/2020,United States,Hispanic,5-17 years,0.0,41.0,NaN
2,04/21/2021,12/29/2019,01/04/2020,By Week,2019/2020,NaN,1.0,01/04/2020,United States,Hispanic,18-29 years,0.0,190.0,NaN
3,04/21/2021,12/29/2019,01/04/2020,By Week,2019/2020,NaN,1.0,01/04/2020,United States,Hispanic,30-39 years,0.0,236.0,NaN
4,04/21/2021,12/29/2019,01/04/2020,By Week,2019/2020,NaN,1.0,01/04/2020,United States,Hispanic,40-49 years,0.0,325.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68899,04/21/2021,01/01/2020,04/17/2021,By Total,2020/2021,NaN,NaN,NaN,10,Unknown,40-49 years,0.0,25.0,NaN
68900,04/21/2021,01/01/2020,04/17/2021,By Total,2020/2021,NaN,NaN,NaN,10,Unknown,50-64 years,NaN,98.0,One or more data cells have counts between 1-9...
68901,04/21/2021,01/01/2020,04/17/2021,By Total,2020/2021,NaN,NaN,NaN,10,Unknown,65-74 years,NaN,89.0,One or more data cells have counts between 1-9...
68902,04/21/2021,01/01/2020,04/17/2021,By Total,2020/2021,NaN,NaN,NaN,10,Unknown,75-84 years,NaN,41.0,One or more data cells have counts between 1-9...
68903,04/21/2021,01/01/2020,04/17/2021,By Total,2020/2021,NaN,NaN,NaN,10,Unknown,85 years and over,NaN,29.0,One or more data cells have counts between 1-9...

In [4]:
#review data types
deaths_df.dtypes

Data As Of                         object
Start Date                         object
End Date                           object
Group                              object
Year                               object
Month                             float64
MMWR Week                         float64
Week-Ending Date                   object
HHS Region                         object
Race and Hispanic Origin Group     object
Age Group                          object
COVID-19 Deaths                   float64
Total Deaths                      float64
Footnote                           object
dtype: object

In [5]:
#drop unneeded comlumns
deaths_df = deaths_df.drop(["Data As Of", "Start Date", "End Date", "Year", "Month", "MMWR Week", "Total Deaths", "Footnote", "Age Group"], axis=1)

In [6]:
#drop unneeded rows
deaths_df = deaths_df.loc[(deaths_df["HHS Region"] != "United States") & (deaths_df["Group"] == "By Week") & (deaths_df ["Race and Hispanic Origin Group"] != "Unknown")]

In [7]:
#drop group column
deaths_df = deaths_df.drop(["Group"], axis=1)

#rename columns
deaths_df = deaths_df.rename(columns={"Week-Ending Date": "Week", "HHS Region": "HHS_Region", "Race and Hispanic Origin Group": "Race", "COVID-19 Deaths": "COVID_Deaths"})

In [8]:
#convert week to datetime
deaths_df["Week"] = pd.to_datetime(deaths_df["Week"])

In [9]:
deaths_df.head()

           Week HHS_Region      Race  COVID_Deaths
4896 2020-01-04         01  Hispanic           0.0
4897 2020-01-04         01  Hispanic           0.0
4898 2020-01-04         01  Hispanic           0.0
4899 2020-01-04         01  Hispanic           0.0
4900 2020-01-04         01  Hispanic           0.0

In [10]:
#group data
#get total deaths, by race, in HHS region 1 by week
deaths_df_1 = deaths_df[deaths_df["HHS_Region"] == "01"]
deaths_df_1 = deaths_df_1.groupby(["Week", "Race"]).sum()["COVID_Deaths"].astype(int)

#get total deaths, by race, in HHS region 2 by week
deaths_df_2 = deaths_df[deaths_df["HHS_Region"] == "02"]
deaths_df_2 = deaths_df_2.groupby(["Week", "Race"]).sum()["COVID_Deaths"].astype(int)

#get total deaths, by race, in HHS region 3 by week
deaths_df_3 = deaths_df[deaths_df["HHS_Region"] == "03"]
deaths_df_3 = deaths_df_3.groupby(["Week", "Race"]).sum()["COVID_Deaths"].astype(int)

#get total deaths, by race, in HHS region 4 by week
deaths_df_4 = deaths_df[deaths_df["HHS_Region"] == "04"]
deaths_df_4 = deaths_df_4.groupby(["Week", "Race"]).sum()["COVID_Deaths"].astype(int)

#get total deaths, by race, in HHS region 5 by week
deaths_df_5 = deaths_df[deaths_df["HHS_Region"] == "05"]
deaths_df_5 = deaths_df_5.groupby(["Week", "Race"]).sum()["COVID_Deaths"].astype(int)

#get total deaths, by race, in HHS region 6 by week
deaths_df_6 = deaths_df[deaths_df["HHS_Region"] == "06"]
deaths_df_6 = deaths_df_6.groupby(["Week", "Race"]).sum()["COVID_Deaths"].astype(int)

#get total deaths, by race, in HHS region 7 by week
deaths_df_7 = deaths_df[deaths_df["HHS_Region"] == "07"]
deaths_df_7 = deaths_df_7.groupby(["Week", "Race"]).sum()["COVID_Deaths"].astype(int)

#get total deaths, by race, in HHS region 8 by week
deaths_df_8 = deaths_df[deaths_df["HHS_Region"] == "08"]
deaths_df_8 = deaths_df_8.groupby(["Week", "Race"]).sum()["COVID_Deaths"].astype(int)

#get total deaths, by race, in HHS region 9 by week
deaths_df_9 = deaths_df[deaths_df["HHS_Region"] == "09"]
deaths_df_9 = deaths_df_9.groupby(["Week", "Race"]).sum()["COVID_Deaths"].astype(int)

#get total deaths, by race, in HHS region 10 by week
deaths_df_10 = deaths_df[deaths_df["HHS_Region"] == "10"]
deaths_df_10 = deaths_df_10.groupby(["Week", "Race"]).sum()["COVID_Deaths"].astype(int)

In [11]:
deaths_df_1.head()

Week        Race
2020-01-04  Hispanic                                         0
            Non-Hispanic American Indian or Alaska Native    0
            Non-Hispanic Asian                               0
            Non-Hispanic Black                               0
            Non-Hispanic More than one race                  0
Name: COVID_Deaths, dtype: int32

In [12]:
#export clean covid death data by HHS region to CSVs
deaths_df.to_csv("Resources\Clean_Data.csv")
deaths_df_1.to_csv("Resources\Clean_Data_HHS1.csv")
deaths_df_2.to_csv("Resources\Clean_Data_HHS2.csv")
deaths_df_3.to_csv("Resources\Clean_Data_HHS3.csv")
deaths_df_4.to_csv("Resources\Clean_Data_HHS4.csv")
deaths_df_5.to_csv("Resources\Clean_Data_HHS5.csv")
deaths_df_6.to_csv("Resources\Clean_Data_HHS6.csv")
deaths_df_7.to_csv("Resources\Clean_Data_HHS7.csv")
deaths_df_8.to_csv("Resources\Clean_Data_HHS8.csv")
deaths_df_9.to_csv("Resources\Clean_Data_HHS9.csv")
deaths_df_10.to_csv("Resources\Clean_Data_HHS10.csv")

In [13]:
#read in vaccine data
JJ_df = pd.read_csv("Resources/Janssen.csv")
Moderna_df = pd.read_csv("Resources/Moderna.csv")
Pfizer_df = pd.read_csv("Resources/Pfizer.csv")

In [14]:
JJ_df

         Jurisdiction Week of Allocations  1st Dose Allocations
0         Connecticut          04/12/2021                  6400
1               Maine          04/12/2021                  2500
2       Massachusetts          04/12/2021                 12300
3       New Hampshire          04/12/2021                  2500
4        Rhode Island          04/12/2021                  2000
..                ...                 ...                   ...
373            Alaska          03/01/2021                  8900
374             Idaho          03/01/2021                 13300
375            Oregon          03/01/2021                 34400
376        Washington          03/01/2021                 60900
377  Federal Entities          03/01/2021                139200

[378 rows x 3 columns]

In [15]:
# create HHS region data
groups = {
    "01": ["Connecticut", "Maine", "Massachusetts", "New Hampshire", "Rhode Island", "Vermont"],
    "02": ["New Jersey", "New York", "Puerto Rico", "Virgin Islands"],
    "03": ["Delaware", "District of Columbia", "Maryland", "Pennsylvania", "Virginia", "West Virginia"],
    "04": ["Alabama", "Florida", "Georgia", "Kentucky", "Mississippi", "North Carolina", "South Carolina", "Tennessee"],
    "05": ["Illinois", "Indiana", "Michigan", "Minnesota", "Ohio", "Wisconsin"],
    "06": ["Arkansas", "Louisiana", "New Mexico", "Oklahoma", "Texas"],
    "07": ["Iowa", "Kansas", "Missouri", "Nebraska"],
    "08": ["Colorado", "Montana", "North Dakota", "South Dakota", "Utah", "Wyoming"],
    "09": ["Arizona", "California", "Hawaii", "Nevada"],
    "10": ["Alaska", "Idaho", "Oregon", "Washington"]
}

##edit week data to reflect when the vaccination would go into effect - aka 2 weeks after distro
weeks = {
    "1/2/21": "12/14/2020",
    "1/9/21" :'12/21/2020',
    "1/16/21" : '12/28/2020',
    "1/23/21" :'12/28/2020',
    "1/30/21" : '01/11/2021',
    "2/6/21" : '01/18/2021',
    "2/13/21" : '01/25/2021',
    "2/20/21" : '02/01/2021',
    "2/27/21" :'02/08/2021',
    "3/6/21" : '02/15/2021',
    "3/13/21" : '02/22/2021',
    "3/20/21" : '03/01/2021',
    "3/27/21" : '03/08/2021',
    "4/3/21" : '03/15/2021',
    "4/10/21" : '03/22/2021',
    "4/17/21" :'03/29/2021',
    "N/A" : '04/05/2021',
    "N/A" : '04/12/2021',
    "N/A" : '04/19/2021',
    "N/A" : '04/26/2021'
}

In [16]:
#clean JJ data
#add HHS region data to JJ DF
JJ_df["HHS_Region"] = (
    JJ_df["Jurisdiction"]
    .apply(lambda x: [k for k in groups.keys() if x in groups[k]])
    .str[0]
    .fillna("Other")
)

#edit weeks
JJ_df["Week"] = (
    JJ_df["Week of Allocations"]
    .apply(lambda x: [k for k in weeks.keys() if x in weeks[k]])
    .str[0]
    .fillna("Other")
)

#rename columns
JJ_df = JJ_df.rename(columns={"1st Dose Allocations": "Vaccinations"})

#drop n/a weeks and columns
JJ_df = JJ_df.drop(["Jurisdiction", "Week of Allocations"], axis = 1)
JJ_df = JJ_df.loc[(JJ_df["Week"] != "N/A") & (JJ_df["Week"] != "Other")]

In [17]:
#convert week to datetime
JJ_df["Week"] = pd.to_datetime(JJ_df["Week"])

In [18]:
#get total JnJ vaccines distributed
Total_JJ = JJ_df.groupby(["Week"]).sum()["Vaccinations"].astype(int)

#get total JnJ vaccines distributed in HHS region 1 by week
JJ_df_1 = JJ_df[JJ_df["HHS_Region"] == "01"]
JJ_df_1 = JJ_df.groupby(["Week"]).sum()["Vaccinations"].astype(int)

#get total JnJ vaccines distributed in HHS region 2 by week
JJ_df_2 = JJ_df[JJ_df["HHS_Region"] == "02"]
JJ_df_2 = JJ_df.groupby(["Week"]).sum()["Vaccinations"].astype(int)

#get total JnJ vaccines distributed in HHS region 3 by week
JJ_df_3 = JJ_df[JJ_df["HHS_Region"] == "03"]
JJ_df_3 = JJ_df.groupby(["Week"]).sum()["Vaccinations"].astype(int)

#get total JnJ vaccines distributed in HHS region 4 by week
JJ_df_4 = JJ_df[JJ_df["HHS_Region"] == "04"]
JJ_df_4 = JJ_df.groupby(["Week"]).sum()["Vaccinations"].astype(int)

#get total JnJ vaccines distributed in HHS region 5 by week
JJ_df_5 = JJ_df[JJ_df["HHS_Region"] == "05"]
JJ_df_5 = JJ_df.groupby(["Week"]).sum()["Vaccinations"].astype(int)

#get total JnJ vaccines distributed in HHS region 6 by week
JJ_df_6 = JJ_df[JJ_df["HHS_Region"] == "06"]
JJ_df_6 = JJ_df.groupby(["Week"]).sum()["Vaccinations"].astype(int)

#get total JnJ vaccines distributed in HHS region 7 by week
JJ_df_7 = JJ_df[JJ_df["HHS_Region"] == "07"]
JJ_df_7 = JJ_df.groupby(["Week"]).sum()["Vaccinations"].astype(int)

#get total JnJ vaccines distributed in HHS region 8 by week
JJ_df_8 = JJ_df[JJ_df["HHS_Region"] == "08"]
JJ_df_8 = JJ_df.groupby(["Week"]).sum()["Vaccinations"].astype(int)

#get total JnJ vaccines distributed in HHS region 9 by week
JJ_df_9 = JJ_df[JJ_df["HHS_Region"] == "09"]
JJ_df_9 = JJ_df.groupby(["Week"]).sum()["Vaccinations"].astype(int)

#get total JnJ vaccines distributed in HHS region 10 by week
JJ_df_10 = JJ_df[JJ_df["HHS_Region"] == "10"]
JJ_df_10 = JJ_df.groupby(["Week"]).sum()["Vaccinations"].astype(int)

In [19]:
Pfizer_df

,Jurisdiction,Week of Allocations,1st Dose Allocations,2nd Dose Allocations
0,Connecticut,04/26/2021,54990,54990
1,Maine,04/26/2021,21060,21060
2,Massachusetts,04/26/2021,105300,105300
3,New Hampshire,04/26/2021,21060,21060
4,Rhode Island,04/26/2021,16380,16380
...,...,...,...,...
1255,Virginia,12/14/2020,72150,72150
1256,Washington,12/14/2020,62400,62400
1257,West Virginia,12/14/2020,16575,16575
1258,Wisconsin,12/14/2020,49725,49725
1259,Wyoming,12/14/2020,4875,4875

In [20]:
#clean Pfizer data
#add HHS region data to Pfizer DF
Pfizer_df["HHS_Region"] = (
    Pfizer_df["Jurisdiction"]
    .apply(lambda x: [k for k in groups.keys() if x in groups[k]])
    .str[0]
    .fillna("Other")
)

#edit weeks
Pfizer_df["Week"] = (
    Pfizer_df["Week of Allocations"]
    .apply(lambda x: [k for k in weeks.keys() if x in weeks[k]])
    .str[0]
    .fillna("Other")
)

#rename columns
Pfizer_df = Pfizer_df.rename(columns={"2nd Dose Allocations": "Vaccinations"})

#drop n/a weeks and columns
Pfizer_df = Pfizer_df.drop(["Jurisdiction", "Week of Allocations"], axis = 1)
Pfizer_df = Pfizer_df.loc[(Pfizer_df["Week"] != "N/A") & (Pfizer_df["Week"] != "Other")]

#convert week to datetime
Pfizer_df["Week"] = pd.to_datetime(Pfizer_df["Week"])

#get total Pfizer vaccines distributed
Total_Pfizer = Pfizer_df.groupby(["Week"]).sum()["Vaccinations"]

#get total Pfizer vaccines distributed in HHS region 1 by week
Pfizer_df_1 = Pfizer_df[Pfizer_df["HHS_Region"] == "01"]
Pfizer_df_1 = Pfizer_df.groupby(["Week"]).sum()["Vaccinations"]

#get total Pfizer vaccines distributed in HHS region 2 by week
Pfizer_df_2 = Pfizer_df[Pfizer_df["HHS_Region"] == "02"]
Pfizer_df_2 = Pfizer_df.groupby(["Week"]).sum()["Vaccinations"]

#get total Pfizer vaccines distributed in HHS region 3 by week
Pfizer_df_3 = Pfizer_df[Pfizer_df["HHS_Region"] == "03"]
Pfizer_df_3 = Pfizer_df.groupby(["Week"]).sum()["Vaccinations"]

#get total Pfizer vaccines distributed in HHS region 4 by week
Pfizer_df_4 = Pfizer_df[Pfizer_df["HHS_Region"] == "04"]
Pfizer_df_4 = Pfizer_df.groupby(["Week"]).sum()["Vaccinations"]

#get total Pfizer vaccines distributed in HHS region 5 by week
Pfizer_df_5 = Pfizer_df[Pfizer_df["HHS_Region"] == "05"]
Pfizer_df_5 = Pfizer_df.groupby(["Week"]).sum()["Vaccinations"]

#get total Pfizer vaccines distributed in HHS region 6 by week
Pfizer_df_6 = Pfizer_df[Pfizer_df["HHS_Region"] == "06"]
Pfizer_df_6 = Pfizer_df.groupby(["Week"]).sum()["Vaccinations"]

#get total Pfizer vaccines distributed in HHS region 7 by week
Pfizer_df_7 = Pfizer_df[Pfizer_df["HHS_Region"] == "07"]
Pfizer_df_7 = Pfizer_df.groupby(["Week"]).sum()["Vaccinations"]

#get total Pfizer vaccines distributed in HHS region 8 by week
Pfizer_df_8 = Pfizer_df[Pfizer_df["HHS_Region"] == "08"]
Pfizer_df_8 = Pfizer_df.groupby(["Week"]).sum()["Vaccinations"]

#get total Pfizer vaccines distributed in HHS region 9 by week
Pfizer_df_9 = Pfizer_df[Pfizer_df["HHS_Region"] == "09"]
Pfizer_df_9 = Pfizer_df.groupby(["Week"]).sum()["Vaccinations"]

#get total Pfizer vaccines distributed in HHS region 10 by week
Pfizer_df_10 = Pfizer_df[Pfizer_df["HHS_Region"] == "10"]
Pfizer_df_10 = Pfizer_df.groupby(["Week"]).sum()["Vaccinations"]

In [21]:
#clean Moderna data
#add HHS region data to Moderna DF
Moderna_df["HHS_Region"] = (
    Moderna_df["Jurisdiction"]
    .apply(lambda x: [k for k in groups.keys() if x in groups[k]])
    .str[0]
    .fillna("Other")
)

#edit weeks
Moderna_df["Week"] = (
    Moderna_df["Week of Allocations"]
    .apply(lambda x: [k for k in weeks.keys() if x in weeks[k]])
    .str[0]
    .fillna("Other")
)

#rename columns
Moderna_df = Moderna_df.rename(columns={"2nd Dose Allocations": "Vaccinations"})

#drop n/a weeks and columns
Moderna_df = Moderna_df.drop(["Jurisdiction", "Week of Allocations"], axis = 1)
Moderna_df = Moderna_df.loc[(Moderna_df["Week"] != "N/A") & (Moderna_df["Week"] != "Other")]

#convert week to datetime
Moderna_df["Week"] = pd.to_datetime(Moderna_df["Week"])

#get total Moderna vaccines distributed
Total_Moderna = Moderna_df.groupby(["Week"]).sum()["Vaccinations"]

#get total Moderna vaccines distributed in HHS region 1 by week
Moderna_df_1 = Moderna_df[Moderna_df["HHS_Region"] == "01"]
Moderna_df_1 = Moderna_df.groupby(["Week"]).sum()["Vaccinations"]

#get total Moderna vaccines distributed in HHS region 2 by week
Moderna_df_2 = Moderna_df[Moderna_df["HHS_Region"] == "02"]
Moderna_df_2 = Moderna_df.groupby(["Week"]).sum()["Vaccinations"]

#get total Moderna vaccines distributed in HHS region 3 by week
Moderna_df_3 = Moderna_df[Moderna_df["HHS_Region"] == "03"]
Moderna_df_3 = Moderna_df.groupby(["Week"]).sum()["Vaccinations"]

#get total Moderna vaccines distributed in HHS region 4 by week
Moderna_df_4 = Moderna_df[Moderna_df["HHS_Region"] == "04"]
Moderna_df_4 = Moderna_df.groupby(["Week"]).sum()["Vaccinations"]

#get total Moderna vaccines distributed in HHS region 5 by week
Moderna_df_5 = Moderna_df[Moderna_df["HHS_Region"] == "05"]
Moderna_df_5 = Moderna_df.groupby(["Week"]).sum()["Vaccinations"]

#get total Moderna vaccines distributed in HHS region 6 by week
Moderna_df_6 = Moderna_df[Moderna_df["HHS_Region"] == "06"]
Moderna_df_6 = Moderna_df.groupby(["Week"]).sum()["Vaccinations"]

#get total Moderna vaccines distributed in HHS region 7 by week
Moderna_df_7 = Moderna_df[Moderna_df["HHS_Region"] == "07"]
Moderna_df_7 = Moderna_df.groupby(["Week"]).sum()["Vaccinations"]

#get total Moderna vaccines distributed in HHS region 8 by week
Moderna_df_8 = Moderna_df[Moderna_df["HHS_Region"] == "08"]
Moderna_df_8 = Moderna_df.groupby(["Week"]).sum()["Vaccinations"]

#get total Moderna vaccines distributed in HHS region 9 by week
Moderna_df_9 = Moderna_df[Moderna_df["HHS_Region"] == "09"]
Moderna_df_9 = Moderna_df.groupby(["Week"]).sum()["Vaccinations"]

#get total Moderna vaccines distributed in HHS region 10 by week
Moderna_df_10 = Moderna_df[Moderna_df["HHS_Region"] == "10"]
Moderna_df_10 = Moderna_df.groupby(["Week"]).sum()["Vaccinations"]

In [22]:
#merge all vaccine DFs together for total vaccine distro
#get total JnJ vaccines distributed
total_vaccine_distro = Total_JJ.add(Total_Pfizer, Total_Moderna, fill_value = 0)

# merge all together, totaling up distributed vaccines by HHS region by week
#sum all the vaccines distributed in HHS region 1
vaccine_distro_1 = JJ_df_1.add(Pfizer_df_1, Moderna_df_1, fill_value = 0)

#sum all the vaccines distributed in HHS region 2
vaccine_distro_2 = JJ_df_2.add(Pfizer_df_2, Moderna_df_2, fill_value = 0)

#sum all the vaccines distributed in HHS region 3
vaccine_distro_3 = JJ_df_3.add(Pfizer_df_3, Moderna_df_3, fill_value = 0)

#sum all the vaccines distributed in HHS region 4
vaccine_distro_4 = JJ_df_4.add(Pfizer_df_4, Moderna_df_4, fill_value = 0)

#sum all the vaccines distributed in HHS region 5
vaccine_distro_5 = JJ_df_5.add(Pfizer_df_5, Moderna_df_5, fill_value = 0)

#sum all the vaccines distributed in HHS region 6
vaccine_distro_6 = JJ_df_6.add(Pfizer_df_6, Moderna_df_6, fill_value = 0)

#sum all the vaccines distributed in HHS region 7
vaccine_distro_7 = JJ_df_7.add(Pfizer_df_7, Moderna_df_7, fill_value = 0)

#sum all the vaccines distributed in HHS region 8
vaccine_distro_8 = JJ_df_8.add(Pfizer_df_8, Moderna_df_8, fill_value = 0)

#sum all the vaccines distributed in HHS region 9
vaccine_distro_9 = JJ_df_9.add(Pfizer_df_9, Moderna_df_9, fill_value = 0)

#sum all the vaccines distributed in HHS region 10
vaccine_distro_10 = JJ_df_10.add(Pfizer_df_10, Moderna_df_10, fill_value = 0)

In [23]:
#export total vaccine data
total_vaccine_distro.to_csv("Resources\Total_Vaccine_Distro.csv")

#export clean vaccine data by HHS region to CSVs
vaccine_distro_1.to_csv("Resources\Vaccine_Data_HHS1.csv")
vaccine_distro_2.to_csv("Resources\Vaccine_Data_HHS2.csv")
vaccine_distro_3.to_csv("Resources\Vaccine_Data_HHS3.csv")
vaccine_distro_4.to_csv("Resources\Vaccine_Data_HHS4.csv")
vaccine_distro_5.to_csv("Resources\Vaccine_Data_HHS5.csv")
vaccine_distro_6.to_csv("Resources\Vaccine_Data_HHS6.csv")
vaccine_distro_7.to_csv("Resources\Vaccine_Data_HHS7.csv")
vaccine_distro_8.to_csv("Resources\Vaccine_Data_HHS8.csv")
vaccine_distro_9.to_csv("Resources\Vaccine_Data_HHS9.csv")
vaccine_distro_10.to_csv("Resources\Vaccine_Data_HHS10.csv")